twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['common/form/theme.html.twig']
    globals:
        storageCdnUrl: '%env(STORAGE_CDN)%'
when@test:
    twig:
        strict_variables: true
