version: "3.8"

volumes:
  database: {}

services:
  database:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: jeunot
      POSTGRES_PASSWORD: jeunot
      POSTGRES_USER: jeunot
    ports:
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql@15/data:rw'

  php:
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/jeunot
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
      - redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/jeunot
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

