name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:15.3-alpine
        env:
          POSTGRES_USER: jeunot
          POSTGRES_PASSWORD: jeunot
          POSTGRES_DB: jeunot
        ports:
          - 5432:5432

      redis:
        image: redis:5-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Init CI environment variables
        # HACK: Symfony won't read from 'env: { DATABASE_URL: ... }', so we need to edit
        # .env directly.
        run: |
          echo "DATABASE_URL=postgresql://jeunot:jeunot@localhost:5432/jeunot" >> .env
          echo "REDIS_URL=redis://localhost:6379" >> .env

      - name: CI
        run: make ci CI=1 BIN_PHP="php" BIN_CONSOLE="php bin/console" BIN_COMPOSER="composer" BIN_NPM="npm" BIN_NPX="npx"

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
